--nazioni(nome)
CREATE TABLE NAZIONI(
    NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY (NOME)
);

--edizioni(anno, nazione ospitante, nazione vincitrice)
CREATE TABLE EDIZIONI (
    ANNO NUMERIC(4) NOT NULL,
    NAZIONE_OSPITANTE VARCHAR(100) NOT NULL,
    NAZIONE_VINCITRICE VARCHAR(100), -- nullable
    PRIMARY KEY (ANNO),
    FOREIGN KEY (NAZIONE_OSPITANTE) REFERENCES NAZIONI(NOME)
    FOREIGN KEY (NAZIONE_VINCITRICE) REFERENCES NAZIONI(NOME)
)

--squadre()
CREATE TABLE SQUADRE (
    EDIZIONE NUMERIC(4) NOT NULL,
    NAZIONE VARCHAR(100) NOT NULL,
    COGNOME_NOME_ALLENATORE VARCHAR(100)
)
--modifica dello schema della tabella
ALTER TABLE SQUADRE
    ADD CONSTRAINT SQUADRE_KEY PRIMARY KEY (EDIZIONE, NAZIONE);
ALTER TABLE SQUADRE
    ADD CONSTRAINT SQUADRE_EDIZIONE_FKEY 
    FOREIGN KEY (EDIZIONE) REFERENCES EDIZIONI(ANNO);
ALTER TABLE SQUADRE
    ADD CONSTRAINT SQUADRE_NAZIONE_FKEY 
    FOREIGN KEY (NAZIONE) REFERENCES NAZIONI(NOME);
ALTER TABLE SQUADRE 
    ALTER COLUMN COGNOME_NOME_ALLENATORE SET NOT NULL;

-- NUOVA SIGLA CIFC: CODE IS FUCKING CODE (@Zambo-dev)

--giocatori(id, cognome nome, anno nascita)
CREATE TABLE GIOCATORI(
    ID NUMERIC(10) NOT NULL PRIMARY KEY,
    COGNOME_NOME VARCHAR(100) NOT NULL,
    ANNO_NASCITA NUMERIC(4) NOT NULL,
)

--convocati
CREATE TABLE CONVOCATI(
    SQUADRA_EDIZIONE NUMERIC(4) NOT NULL,
    SQUADRA_NAZIONE VARCHAR(200) NOT NULL,
    NUMERO_MAGLIA INTEGER NOT NULL,
    GIOCATORE NUMERIC(10) NOT NULL REFERENCES GIOCATORI(ID),
    PRIMARY KEY (SQUADRA_EDIZIONE, SQUADRA_NAZIONE, NUMERO_MAGLIA)
    FOREIGN KEY (SQUADRA_EDIZIONE, SQUADRA_NAZIONE) REFERENCES SQUADRE(EDIZIONE, NAZIONE)
)
